import { Inter } from "next/font/google";
import "./globals.css";
import UIProvider from "./providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <main className="dark text-foreground bg-background">
          <UIProvider>{children}</UIProvider>
        </main>
      </body>
    </html>
  );
}
